### ISSUE TITLE
After activation error

### ISSUE THREAD

**Issue by Brandinwebdesign** [TAGGRS/taggrs-wordpress#1]
When I use the plugin I immediately get an error on the front of the website.
The rear continues to work.
I get the following error:

Fatal error: Uncaught Error: Call to undefined function is_product() in /home/richards/domains/brandinwebdesign.nl/public_html/wp-content/plugins/taggrs-wordpress/includes/events/view_item.php:15 Stack trace: # 0 /home/**/**/**.nl/public_html/wp-includes/class-wp-hook.php(324): wc_gtm_view_item() #1 /home/**/**/**.nl/public_html/wp-includes /class-wp-hook.php(348): WP_Hook->apply_filters() #2 /home/**/**/**.nl/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/**/**/**.nl/public_html/wp-includes/general-template.php(3068): do_action() #4 /home/**/**/**.nl/public_html/wp-content/ plugins/oxygen/component-framework/oxygen-main-template.php(268): wp_footer() #5 /home/**/**/**.nl/public_html/wp-includes/template-loader.php(106): include('...') #6 /home/**/**/**.nl/public_html/wp-blog-header.php(19): require_once('...') #7 /home/**/**/**.nl/public_html/index.php(17): require('...') #8 {main} thrown in /home/**/**/**.nl/public_html/wp-content/plugins/taggrs- wordpress/includes/events/view_item.php on line 15

**Comment by BruceKristelijn** [comment]
Sorry for the late response @Brandinwebdesign, what version of wordpress and woocommerce are you using?

Please test the latest [development branch](https://github.com/TAGGRS/taggrs-wordpress/tree/development) [commit](https://github.com/TAGGRS/taggrs-wordpress/commit/933149c3f0c2b6212e06f937f3159e615a64827e) which contains multiple improvements & fixes.
This zip can be directly installed: [taggrs-wordpress-plugin.zip](https://github.com/TAGGRS/taggrs-wordpress/files/14547145/taggrs-wordpress-plugin.zip)

**Comment by BruceKristelijn** [comment]
I will close this because of inactivity. Feel free to reopen of create a new issue any time!
