### ISSUE TITLE
Error in refund event

### ISSUE THREAD

**Issue by gjportegies** [TAGGRS/taggrs-wordpress#6]
The refund event falsely assumes the product on the order line_item still exists.
In our case the product does not exists in the store anymore resulting in the following error:

```
Error: Call to a member function get_id() on bool in /wp-content/plugins/taggrs-wordpress-plugin/includes/events/refund.php:12
```

The event should check if the product exists before using the object.

**Comment by BruceKristelijn** [comment]
Thank you for reporting this issue. 

In the foreach loop I have added a empty check to skip empty / non existing products. I also noticed the category logging not working properly so I've added this aswell.

Feel free to test it on [this branch](https://github.com/TAGGRS/taggrs-wordpress/tree/6-error-in-refund-event) to make sure it works for you aswell.
