### ISSUE TITLE
Error in view_promotions event

### ISSUE THREAD

**Issue by gjportegies** [TAGGRS/taggrs-wordpress#7]
Log file is full with errors from the view_promotions event.

`Undefined variable $promotion_id in /wp-content/plugins/taggrs-wordpress-plugin/includes/events/view_promotion.php on line 52`

`Undefined variable $promotion_code in /wp-content/plugins/taggrs-wordpress-plugin/includes/events/view_promotion.php on line 53`

`Undefined variable $promotion_items in /wp-content/plugins/taggrs-wordpress-plugin/includes/events/view_promotion.php on line 54`

The 3 variables mentioned above are only defined in the foreach loop above. But if the promotions array is empty is will result in the undefined variable errors.

**Comment by BruceKristelijn** [comment]
Thanks again for reporting this issue. Right now I am having some trouble testing & fixing the issue. 

I will get back to this on asap.
